ROW_COMPANY_NAME = 0
ROW_TITLE = ROW_COMPANY_NAME + 2
ROW_CODE = ROW_TITLE + 1

ROW_VENDOR_NAME = ROW_CODE + 2
ROW_VENDOR_BANKS = ROW_VENDOR_NAME + 2
ROW_EXTRA_INFO = ROW_VENDOR_BANKS +1
ROW_TABLE_HEAD = ROW_EXTRA_INFO + 2

COL_NO = 0
COL_NAME = COL_NO + 1
COL_SPECIFICATION = COL_NAME + 1
COL_DESCRIPTION = COL_SPECIFICATION + 1
COL_BRAND = COL_DESCRIPTION + 1
COL_HSCODE = COL_BRAND + 1
COL_QTY = COL_HSCODE + 1
COL_UOM = COL_QTY + 1
COL_UNIT_PRICE = COL_UOM + 1
COL_AMOUNT = COL_UNIT_PRICE + 1



