STOCK_OUT_GUDANG_UTAMA = "STOCK OUT GUDANG UTAMA"
RECEIPTS = "Receipts"
SO_KITCHEN_HARIAN = "SO KITCHEN HARIAN"
PRODUCTION = "Production"
WASTE = "Waste"
RESTOCK="Restock Kitchen"
STOCK_OPNAME_ECER="STOCK OPNAME ECER"

