# WEEKLY EXCEL
ROW_TITLE = 0
ROW_COMPANY_NAME = ROW_TITLE + 1
ROW_PERIOD = ROW_COMPANY_NAME + 1
ROW_TABLE_HEAD = ROW_PERIOD + 2

COL_NO = 0  # PERIOD
# COL_PAID_VIA = COL_NO + 1
COL_NAMA = COL_NO + 1
COL_HARI_KERJA = COL_NAMA + 1
COL_TELAT = COL_HARI_KERJA + 1
COL_KETERANGAN = COL_TELAT + 1
COL_TOTAL_HARI = COL_KETERANGAN + 1
COL_UANG_MAKAN_KOTA = COL_TOTAL_HARI + 1
COL_TOTAL_HARI_LUAR = COL_UANG_MAKAN_KOTA + 1
COL_UANG_MAKAN_LUAR = COL_TOTAL_HARI_LUAR + 1
COL_KETERANGAN_UANG_MAKAN_LUAR = COL_UANG_MAKAN_LUAR + 1
COL_TOTAL_LEMBUR = COL_KETERANGAN_UANG_MAKAN_LUAR + 1
COL_UPAH_LEMBUR = COL_TOTAL_LEMBUR + 1
COL_KETERANGAN_LEMBUR = COL_UPAH_LEMBUR + 1
COL_TOTAL_UANG_MAKAN = COL_KETERANGAN_LEMBUR + 1
COL_TTD_1 = COL_TOTAL_UANG_MAKAN + 1

COL_PERIOD_VALUE = COL_NO + 2

# MONTHLY EXCEL

# SHEET_OVERTIME
ROW_TITLE_OVERTIME = 0
ROW_COMPANY_NAME_OVERTIME = ROW_TITLE_OVERTIME + 1
ROW_MONTH = ROW_COMPANY_NAME_OVERTIME + 1
ROW_TABLE_HEAD_OVERTIME = ROW_MONTH + 2

COL_NO_OVERTIME = 0
COL_NAME_OVERTIME = COL_NO_OVERTIME + 1
COL_OVERTIME_DURATION = COL_NAME_OVERTIME + 1
COL_OVERTIME_AMOUNT = COL_OVERTIME_DURATION + 1
COL_SIGN_OVERTIME1 = COL_OVERTIME_AMOUNT + 1
COL_SIGN_OVERTIME2 = COL_SIGN_OVERTIME1 + 1

# SHEET DILIGENCE
ROW_TITLE_DILIGENCE = 0
ROW_COMPANY_NAME_DILIGENCE = ROW_TITLE_DILIGENCE + 1
ROW_MONTH_DILIGENCE = ROW_COMPANY_NAME_DILIGENCE + 1
ROW_TABLE_HEAD_DILIGENCE = ROW_MONTH_DILIGENCE + 2

COL_NO_DILIGENCE = 0
COL_NAME_DILIGENCE = COL_NO_DILIGENCE + 1
COL_TOTAL_DILIGENCE = COL_NAME_DILIGENCE + 1
COL_SIGN_DILIGENCE1 = COL_TOTAL_DILIGENCE + 1
COL_SIGN_DILIGENCE2 = COL_SIGN_DILIGENCE1 + 1

# SHEET MONTHLY REPORT
ROW_TITLE_REPORT = 0
ROW_COMPANY_NAME_REPORT = ROW_TITLE_REPORT + 1
ROW_MONTH_REPORT = ROW_COMPANY_NAME_REPORT + 1
ROW_TABLE_HEAD_REPORT = ROW_MONTH_REPORT + 2

COL_NO_REPORT = 0
COL_NAMA_REPORT = COL_NO_REPORT + 1
COL_WEEK1 = COL_NAMA_REPORT + 1
COL_WEEK2 = COL_WEEK1 + 1
COL_WEEK3 = COL_WEEK2 + 1
COL_WEEK4 = COL_WEEK3 + 1

# ADJUSTABLE
COL_WEEK5 = COL_WEEK4 + 1

COL_UM_AN = COL_WEEK5 + 1
COL_TOTAL_UM = COL_UM_AN + 1
COL_LEMBUR = COL_TOTAL_UM + 1
COL_KERAJINAN = COL_LEMBUR + 1
COL_INSENTIF = COL_KERAJINAN + 1
COL_OTHERS = COL_INSENTIF + 1
COL_TOTAL = COL_OTHERS + 1