{
    'name': 'SSS Addons',
    'author': 'SSS Group',
    'version': '0.1',
    'depends': ['account', 'purchase', 'sale', 'sales_team', 'payment', 'portal', 'utm', 'hr', 'purchase_order_type'],
    'data': [
        'wizard/purchase_make_payment_request_views.xml',
        'views/purchase_requisition_form.xml',
        'views/purchase_form.xml',
        'views/purchase_agreement_report.xml',
        'views/report_purchaseagreement.xml',
        'views/res_partner_form.xml',
        'views/product.xml',
        'views/efaktur.xml',
        'views/sale.xml',
        'views/mrp_view.xml',
        'views/stock_picking_form.xml',
        'views/stock_inventory.xml',
        'wizard/print_payment_summary_view.xml',
        'wizard/print_picking_list_view.xml',
        'views/account_move_form.xml',
        'views/account_payment_form.xml',
        'views/purchase_order_type.xml',
        'wizard/sale_make_invoice_advance_views.xml',
        'report/account_move_invoice_ncr.xml',
        'report/account_move_pelunasan_ncr.xml',
        'report/account_move_tagihan_ncr.xml',
        'report/account_move_tanda_terima_ncr.xml',
        'report/account_payment_bukti_pembayaran_ncr.xml',
        'report/purchase_agreement_report.xml',
        'report/purchase_agreement_xlsx.xml',
        'report/report_survey.xml',
        'report/sale_proforma_invoice_sp.xml',
        'report/stock_inventory_stock_adjustment.xml',
        'report/stock_picking_dbm_sparepart.xml',
        'report/stock_picking_delivery_slip_ncr.xml',
        'report/stock_picking_delivery_slip_ncr_kecil.xml',
        'report/stock_picking_delivery_sp.xml',
        'report/stock_picking_delivery_sticker.xml',
        'report/stock_picking_report_mutasisj.xml',
        # 'views/templates.xml',

    ],
    'qweb': [
    ],
    'sequence': 3,
    'auto_install': False,
    'installable': True,
    'application': True,
    'category': 'SSS Odoo Addons',
    'summary': 'Odoo Addons Special For SSS Group',
    'license': 'OPL-1',
    'website': 'https://sss-id.yasukapower.com/',
    'description': '-'
}
