ROW_TITLE = 0
ROW_COMPANY_NAME = ROW_TITLE + 1
ROW_MONTH = ROW_COMPANY_NAME + 1
ROW_DATE = ROW_MONTH + 1
ROW_TABLE_HEAD = ROW_DATE + 2

COL_NO = 0  # PERIOD
COL_PAID_VIA = COL_NO + 1
COL_NAMA = COL_PAID_VIA + 1
COL_JABATAN = COL_NAMA + 1
COL_HARI_KERJA = COL_JABATAN + 1
COL_TELAT = COL_HARI_KERJA + 1
COL_KETERANGAN = COL_TELAT + 1
COL_TOTAL_HARI = COL_KETERANGAN + 1
COL_UANG_MAKAN_KOTA = COL_TOTAL_HARI + 1
COL_TOTAL_HARI_LUAR = COL_UANG_MAKAN_KOTA + 1
COL_UANG_MAKAN_LUAR = COL_TOTAL_HARI_LUAR + 1
COL_KETERANGAN_UANG_MAKAN_LUAR = COL_UANG_MAKAN_LUAR + 1
COL_TOTAL_UANG_MAKAN = COL_KETERANGAN_UANG_MAKAN_LUAR + 1
COL_TTD_1 = COL_TOTAL_UANG_MAKAN + 1
COL_TTD_2 = COL_TTD_1 + 1

COL_PERIOD_VALUE = COL_NO + 2
