ROW_HEADER = 0
ROW_PRODUCT_NAME = ROW_HEADER + 3
ROW_START_COL = ROW_PRODUCT_NAME + 3

COL_PRODUCT = 0
COL_BOM = COL_PRODUCT + 1
COL_QTY = COL_BOM + 1
COL_UOM = COL_QTY + 1
COL_PRODUCT_COST = COL_UOM + 1
COL_BOM_COST = COL_PRODUCT_COST + 1
COL_LOCATION = COL_BOM_COST + 1